# Generated by Django 3.0.5 on 2020-05-04 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_uvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagion_covid', models.BooleanField()),
                ('contagion_covid_days', models.IntegerField()),
                ('cough', models.BooleanField()),
                ('day', models.DateField(auto_now_add=True)),
                ('degrees_thermometer', models.IntegerField()),
                ('diarrhea', models.BooleanField()),
                ('difficulty_breathing', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('thermometer_temperature', models.BooleanField()),
                ('threw_up', models.BooleanField()),
                ('transmission_oms', models.BooleanField()),
                ('transmission_oms_days', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
        ),
    ]
