# Generated by Django 3.0.5 on 2020-05-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='dep_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipalities', to='department.Department'),
        ),
    ]
