# Generated by Django 3.0.5 on 2020-05-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.IntegerField(unique=True)),
                ('name', models.IntegerField(unique=True)),
            ],
        ),
    ]
