# Generated by Django 3.0.6 on 2020-05-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_code',
        ),
        migrations.AddField(
            model_name='department',
            name='departament_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
